name: Scala CI

on:
  push:
    branches-ignore:
      - "update/**"
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need the git history for sbt-dynver to determine the version
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: temurin
      - uses: sbt/setup-sbt@v1
      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/local/
            ~/.ivy2/cache/
            ~/.sbt/
            ~/.coursier/
          key: ${{hashFiles('**/*.sbt')}}
      - name: Run tests
        run: sbt test scripted
      - name: Publish to Maven Central Repository
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
        if: ${{ env.GITHUB_PERSONAL_ACCESS_TOKEN != '' && github.event_name != 'pull_request' }}
        run: sbt "set every Seq(sonatypeSessionName := \"${{github.workflow}} ${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}-$$ 2.12.20\", publishTo := sonatypePublishToBundle.value)" publishSigned sonatypeBundleRelease
